version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/next-app
#    command: npm run dev
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
